import { ChevronRight } from 'lucide-react';
import SiteHeader from '../components/SiteHeader';
import SiteFooter from '../components/SiteFooter';
import PageHero from '../components/PageHero';

const pointUses=['wykrywanie zmian zapalnych i kontrola gojenia tkanek okołowierzchołkowych','ocena wypełnień, przyzębia oraz urazów zębów i kości','planowanie, prowadzenie i kontrola leczenia endodontycznego','ocena korzeni przed ekstrakcją oraz kontrola po wszczepieniu implantu'];
const panoramaUses=['zaawansowana próchnica, stany zapalne i zęby zatrzymane','planowanie leczenia kanałowego, protetycznego i ortodontycznego','przygotowanie do ekstrakcji, zabiegów chirurgicznych i implantacji','urazy twarzoczaszki i podejrzenie zmian chorobowych'];
const cbctUses=['ocena szczęki, żuchwy, uzębienia, zatok i jamy nosowej','precyzyjne planowanie implantów i zabiegów chirurgicznych','diagnostyka kanałów oraz morfologii korzeni','lokalizacja źródła bólu i zakresu zmian patologicznych'];

function List({items}){return <ul className="rtg-editorial-list">{items.map(x=><li key={x}>{x}</li>)}</ul>}

export default function RtgPage(){return <main><SiteHeader/>
  <PageHero title="Pracownia RTG" image="/page-heroes/rtg.png" position="center 48%"/>
  <nav className="rtg-jump" aria-label="Kategorie badań"><div className="shell"><a href="#pracownia">Pracownia</a><a href="#punktowe">Zdjęcia punktowe</a><a href="#pantomografia">Pantomografia</a><a href="#cbct">Tomografia CBCT</a><a href="#cefalometria">Cefalometria</a><a href="#bezpieczenstwo">Bezpieczeństwo</a></div></nav>

  <article className="rtg-editorial">
    <section id="pracownia" className="shell rtg-editorial-intro"><div><p className="eyebrow"><span/> PRACOWNIA RTG</p><h2>Diagnostyka, która pozwala dobrze zaplanować leczenie.</h2><p className="lead">Badania rentgenowskie pomagają rozpoznawać zmiany patologiczne, planować zabiegi i kontrolować przebieg leczenia.</p><p>Ptak Stomatologia dysponuje pantomografem cyfrowym i tomografem komputerowym Smart Plus firmy Vatech z ramieniem cefalometrycznym. Urządzenie zapewnia wysoką jakość obrazu przy możliwie niskiej dawce promieniowania.</p><p>Badania wykonujemy dla pacjentów kliniki oraz osób skierowanych z innych gabinetów — po wcześniejszym ustaleniu terminu w rejestracji.</p></div><img src="/page-heroes/rtg.png" alt="Aparat RTG w Ptak Stomatologia"/></section>

    <section className="rtg-editorial-band"><div className="shell"><p className="eyebrow light"><span/> ZŁOTY STANDARD</p><h2>Wysoka jakość obrazu przy niskiej dawce promieniowania.</h2><p>Krótki czas naświetlania ogranicza ekspozycję i zwiększa komfort badania. Zdjęcie panoramiczne trwa 7–14,1 sekundy, CBCT 18 sekund, a cefalometria 1,9–3,9 sekundy.</p></div></section>

    <section id="punktowe" className="shell rtg-editorial-section"><div className="rtg-editorial-copy"><p className="eyebrow"><span/> BADANIE WEWNĄTRZUSTNE</p><h2>Zdjęcia punktowe</h2><p>Zdjęcie punktowe obejmuje pojedynczy ząb, dwa lub trzy zęby. Wykonujemy również zdjęcia zgryzowe oraz zgryzowo-skrzydłowe. Dzięki radiowizjografii cyfrowej obraz pojawia się na monitorze w ciągu kilku sekund.</p><h3>Najczęstsze wskazania</h3><List items={pointUses}/><p className="rtg-note"><b>Bez skierowania:</b> zdjęcie punktowe można wykonać bez skierowania lekarza.</p></div><figure><img src="https://ptakstomatologia.pl/wp-content/uploads/2024/11/close-up-dentist-instruments.jpg" alt="Cyfrowa diagnostyka stomatologiczna"/></figure></section>

    <section id="pantomografia" className="rtg-editorial-section rtg-editorial-alt"><div className="shell"><figure><img src="https://ptakstomatologia.pl/wp-content/uploads/2024/11/Zdjecia-RTG-ze-strony-moze-mozna-wykorzystac.webp" alt="Obrazy diagnostyczne RTG"/></figure><div className="rtg-editorial-copy"><p className="eyebrow"><span/> PEŁNY OBRAZ UZĘBIENIA</p><h2>Zdjęcie panoramiczne OPG</h2><p>Panorama przedstawia całe uzębienie i struktury twarzoczaszki. Jest wykorzystywana w stomatologii, ortodoncji i chirurgii szczękowo-twarzowej, ponieważ ułatwia zaplanowanie leczenia i zabiegów.</p><h3>Najczęstsze wskazania</h3><List items={panoramaUses}/></div></div></section>

    <section id="cbct" className="shell rtg-editorial-section"><div className="rtg-editorial-copy"><p className="eyebrow"><span/> OBRAZOWANIE TRÓJWYMIAROWE</p><h2>Tomografia CBCT</h2><p>Tomografia wiązki stożkowej tworzy precyzyjny, trójwymiarowy obraz jamy ustnej, szczęki, żuchwy i okolicznych tkanek. Jest szczególnie pomocna w endodoncji, implantologii i chirurgii stomatologicznej.</p><h3>Zastosowania badania</h3><List items={cbctUses}/><p className="rtg-fields-text"><b>Pola obrazowania:</b> 12 × 9 cm, 10 × 8,5 cm dla osoby dorosłej, 10 × 7 cm dla dziecka oraz 5 × 5 cm — mikrotomografia.</p></div><figure><img src="https://ptakstomatologia.pl/wp-content/uploads/2024/11/Pracownia-RTG.jpg" alt="Tomograf komputerowy w pracowni RTG"/></figure></section>

    <section id="cefalometria" className="rtg-editorial-section rtg-editorial-alt"><div className="shell"><figure><img src="/gallery/galeria-04.jpg" alt="Gabinet Ptak Stomatologia"/></figure><div className="rtg-editorial-copy"><p className="eyebrow"><span/> DIAGNOSTYKA ORTODONTYCZNA</p><h2>Cefalometria</h2><p>Zdjęcie cefalometryczne pokazuje czaszkę w projekcji bocznej wraz ze zgryzem, kośćmi oraz tkankami miękkimi i twardymi twarzy. Pomaga określić anatomiczne przyczyny wady zgryzu, zaplanować leczenie ortodontyczne i oceniać jego postępy.</p></div></div></section>

    <section id="bezpieczenstwo" className="shell rtg-editorial-safety"><div><p className="eyebrow"><span/> BEZPIECZEŃSTWO</p><h2>Ochrona radiologiczna pacjenta</h2><p>Stosujemy zasadę ALARA — dawkę promieniowania ograniczamy do najniższego poziomu, który pozwala uzyskać obraz o odpowiedniej wartości diagnostycznej.</p><p>Zdjęcia punktowe nie wymagają skierowania. Badania zewnątrzustne — panoramiczne, CBCT i cefalometria — wykonujemy na podstawie czytelnego skierowania od lekarza.</p></div><div><h3>RTG a ciąża</h3><p>Kobieta w ciąży lub podejrzewająca ciążę powinna poinformować personel przed badaniem. Badania panoramiczne, CBCT i cefalometryczne są w ciąży przeciwwskazane poza szczególnymi sytuacjami medycznymi.</p><a href="/kontakt">Umów termin badania <ChevronRight/></a></div></section>
  </article>
  <section className="cta-band"><div className="shell"><div><p className="eyebrow light"><span/> REJESTRACJA</p><h2>Umów badanie RTG w Wadowicach</h2></div><a className="btn primary" href="tel:+48664065582">Zadzwoń: 664 06 55 82</a></div></section><SiteFooter/>
</main>}
