'use client';
import { useState } from 'react';
import { ArrowRight, ChevronDown, Phone } from 'lucide-react';
import SiteHeader from '../components/SiteHeader';
import SiteFooter from '../components/SiteFooter';
import PageHero from '../components/PageHero';

const groups=[
 ['Stomatologia zachowawcza',[['Opłata za nieodwołaną wizytę — każde 30 min','100 zł'],['Badanie wewnątrzustne, diagram, konsultacja','100–300 zł'],['Badanie kontrolne z diagramem','80 zł'],['Znieczulenie komputerowe','70 zł'],['Znieczulenie tradycyjne','50 zł'],['Wypełnienie zęba stałego','350–450 zł'],['ICON — leczenie przebarwień szkliwa, 1 ząb','250–300 zł'],['Biodentyna dodatkowo do wypełnienia','180 zł'],['Licówka kompozytowa / bonding','600–700 zł'],['Inlay / onlay kompozytowy bezpośredni','500–600 zł'],['Leczenie kanałowe — 1 kanał','800 zł'],['Leczenie kanałowe — 2 kanały','1 000 zł'],['Leczenie kanałowe — 3 kanały','1 200 zł'],['Leczenie kanałowe — 4 kanały','1 400 zł'],['Leczenie przez koronę protetyczną — dodatkowo','100 zł'],['Powtórne leczenie kanałowe — dodatkowo','100–500 zł'],['Czasowe wypełnienie 1 kanału','150 zł'],['Leczenie chorób śluzówki jamy ustnej','100 zł'],['Badanie żywotności zęba, RTG','100 zł'],['Wizyta doraźna','300–350 zł'],['Usunięcie złamanego narzędzia endodontycznego lub wkładu koronowo-korzeniowego','od 250 zł'],['Zamknięcie perforacji','od 250 zł']], 'Ceny leczenia kanałowego obejmują znieczulenie, zdjęcie RTG, mechaniczne opracowanie, pracę w mikroskopie lub lupach oraz wypełnienie ciepłą gutaperką.'],
 ['Chirurgia stomatologiczna',[['Usunięcie zęba','350–450 zł'],['Chirurgiczne usunięcie zęba','400–500 zł'],['Szycie rany poekstrakcyjnej','80 zł'],['Usunięcie zęba mądrości','400–500 zł'],['Usunięcie zatrzymanego zęba mądrości','700–900 zł'],['Resekcja zęba 1–3 z wypełnieniem wstecznym MTA','od 550–800 zł'],['Podcięcie wędzidełka wargi lub języka','350 zł'],['Odsłonięcie zęba mądrości','200 zł'],['Plastyka połączenia ustno-zatokowego','400 zł'],['Leczenie stanu zapalnego zębodołu po usunięciu','100–150 zł'],['Wyłuszczenie torbieli','400 zł'],['Wypełnienie ubytku poekstrakcyjnego materiałem kościozastępczym','500–3 000 zł'],['Procedura zachowania wyrostka zębodołowego / zębodołu','od 600 zł'],['Osocze bogatopłytkowe','700 zł'],['Badanie histologiczno-patologiczne','od 150 zł']], 'Ceny obejmują znieczulenie. W przypadku znieczulenia komputerowego: +70 zł.'],
 ['Implantologia',[['Cennik','w trakcie przygotowania']]],
 ['Ortodoncja',[['Cennik','w trakcie przygotowania']]],
 ['Stomatologia dziecięca',[['Wizyta adaptacyjna','150 zł'],['Wypełnienie zęba mlecznego — kolorowe lub białe','250–300 zł'],['Usunięcie zęba mlecznego','250–300 zł'],['Lakierowanie zębów mlecznych','250 zł'],['Lakowanie — 1 ząb','150 zł'],['Leczenie endodontyczne zęba mlecznego — 1 kanał','300 zł','Każdy kolejny kanał +250 zł.'],['Leczenie amputacyjne miazgi zęba','250 zł'],['Niewykorzystany zestaw diagnostyczny','50 zł']]],
 ['Protetyka',[['Korona porcelanowa na podbudowie metalowej ze schodkiem ceramicznym (margin)','1 500 zł'],['Most porcelanowy ceramiczno-metalowy — 1 punkt','1 500 zł'],['Korona całoceramiczna z tlenku cyrkonu','od 1 800 zł'],['Zdjęcie korony / mostu — 1 punkt','50 zł'],['Korona tymczasowa — 1 punkt','50 zł'],['Licówka ceramiczna','1 900 zł'],['Licówka kompozytowa','600–700 zł'],['Inlay / onlay ceramiczny','1 200 zł'],['Inlay / onlay kompozytowy bezpośredni','500–600 zł'],['Proteza całkowita','1 700 zł'],['Proteza szkieletowa','2 500–3 000 zł'],['Wkład koronowo-korzeniowy z włókna szklanego','300 zł'],['Odbudowa kompozytowa na 1 wkładzie','600 zł'],['Odbudowa kompozytowa na 2 wkładach','650 zł'],['Proteza szkieletowa bezklamrowa','wycena indywidualna','Cena zależy od rodzaju i liczby elementów retencyjnych.']]],
 ['Periodontologia',[['Badanie periodontologiczne','300 zł'],['SRP — ćwiartka uzębienia','800 zł'],['Szynowanie zębów — 1 punkt','130 zł']]],
 ['Profilaktyka i higienizacja',[['Usunięcie kamienia + piaskowanie','340–390 zł'],['Lakierowanie — 1 łuk / 2 łuki','100 zł / 150 zł'],['Kamień + piaskowanie + lakierowanie','360–400 zł']]],
 ['Stomatologia estetyczna',[['Wybielanie zębów metodą nakładkową','950 zł'],['Wybielanie zęba martwego','450 zł']]],
 ['Diagnostyka RTG',[['Zdjęcie punktowe','30–50 zł'],['Zdjęcie panoramiczne OPG','110 zł'],['Tomografia szczęki i żuchwy','270 zł'],['Tomografia szczęki lub żuchwy','220 zł'],['Mikrotomografia','130 zł'],['Zdjęcie cefalometryczne','100 zł']]]
];

export default function PricePage(){const [open,setOpen]=useState(-1);return <main><SiteHeader/><PageHero title="Cennik" image="/page-heroes/cennik.png" position="center 48%"/>
  <section className="price-intro"><div className="shell price-intro-compact"><div><p className="eyebrow"><span/> CENNIK</p><h2>Usługi stomatologiczne<br/>od 02.2026 r.</h2></div><a href="tel:+48664065582"><Phone/> 664 06 55 82</a></div></section>
  <section className="price-catalog section"><div className="shell"><div className="price-list">{groups.map(([title,rows,note],i)=><article className={`price-group ${open===i?'open':''}`} key={title}><button onClick={()=>setOpen(open===i?-1:i)} aria-expanded={open===i}><span>{String(i+1).padStart(2,'0')}</span><h2>{title}</h2><ChevronDown/></button><div className="price-panel">{note&&<p className="price-category-note">{note}</p>}{rows.map(([name,price,desc])=><div className="catalog-row" key={name}><div><h3>{name}</h3>{desc&&<p>{desc}</p>}</div><b>{price}</b></div>)}</div></article>)}</div><div className="card-payment"><div><span className="payment-visa">VISA</span><span className="payment-master"><i/><i/></span><span className="payment-maestro"><i/><i/></span></div><strong>Tu zapłacisz kartą</strong></div></div></section>
  <section className="cta-band"><div className="shell"><div><p className="eyebrow light"><span/> KONSULTACJA</p><h2>Porozmawiajmy o leczeniu</h2></div><a className="btn primary" href="/#kontakt">Umów konsultację <ArrowRight/></a></div></section><SiteFooter/></main>}
