import { ArrowDown, ArrowRight, Check, Phone } from 'lucide-react';
import SiteHeader from '../components/SiteHeader';
import SiteFooter from '../components/SiteFooter';
import { offerServices } from '../data';

export default function Oferta(){return <main><SiteHeader/>
  <section className="subhero offer-hero"><div className="shell"><p className="eyebrow light"><span/> OFERTA</p><h1>Kompleksowe leczenie.<br/><em>Jasno wyjaśnione.</em></h1><p>Najpierw diagnoza i rozmowa. Potem przejrzysty plan, kolejność etapów i rozwiązania dopasowane do Twoich potrzeb.</p><a className="btn primary" href="#zakres">Zobacz zakres leczenia <ArrowDown size={18}/></a></div></section>
  <section className="offer-index" id="zakres"><div className="shell"><div className="section-head split"><div><p className="eyebrow"><span/> W CZYM MOŻEMY POMÓC</p><h2>Wybierz obszar</h2></div><p>Każdy przypadek zaczynamy od konsultacji. Poniższe informacje pomagają zorientować się w możliwościach leczenia.</p></div><div className="offer-index-grid">{offerServices.map((s,i)=><a href={`#${s.slug}`} key={s.slug}><small>{String(i+1).padStart(2,'0')}</small><span>{s.title}</span><ArrowRight/></a>)}</div></div></section>
  <section className="offer-sections">{offerServices.map((s,i)=><article className="offer-detail" id={s.slug} key={s.slug}><div className="shell offer-detail-grid"><div className="offer-photo"><img src={s.image} alt={`${s.title} w Ptak Stomatologia`}/><span>{String(i+1).padStart(2,'0')}</span></div><div className="offer-copy"><p className="eyebrow"><span/> {s.kicker}</p><h2>{s.title}</h2><p className="offer-intro">{s.intro}</p><div className="offer-columns"><div><h3>Kiedy warto się zgłosić?</h3><ul>{s.when.map(x=><li key={x}><Check/>{x}</li>)}</ul></div><div><h3>Zakres leczenia</h3><ul>{s.scope.map(x=><li key={x}><Check/>{x}</li>)}</ul></div></div><div className="offer-actions"><a className="btn primary" href="/#kontakt">Zapytaj o leczenie <ArrowRight size={18}/></a><a href="tel:+48664065582" className="text-link"><Phone size={17}/> 664 06 55 82</a></div></div></div></article>)}</section>
  <section className="offer-bottom"><div className="shell"><p className="eyebrow light"><span/> PIERWSZY KROK</p><h2>Nie musisz wiedzieć,<br/><em>jakiego leczenia potrzebujesz.</em></h2><p>Opowiedz nam, co Cię niepokoi. Podczas konsultacji ocenimy sytuację i przedstawimy możliwe rozwiązania.</p><a className="btn primary" href="/#kontakt">Umów konsultację <ArrowRight size={18}/></a></div></section><SiteFooter/></main>}
