import { ArrowRight } from 'lucide-react';
import SiteHeader from '../components/SiteHeader';
import SiteFooter from '../components/SiteFooter';
import PageHero from '../components/PageHero';

const team = [
  {name:'Grzegorz Ptak',role:'lekarz dentysta, implantolog, założyciel gabinetu PTAK STOMATOLOGIA',image:'/ptak/grzegorz.jpg',bio:['Absolwent Wydziału Lekarsko-Dentystycznego Collegium Medicum Uniwersytetu Jagiellońskiego. Założyciel gabinetu, który od 2021 roku działa w nowej siedzibie jako PTAK STOMATOLOGIA.','Ukończył międzynarodowe Curriculum Implantologiczne DGOI. Łączy wieloletnie doświadczenie kliniczne z ciepłym, życzliwym podejściem do pacjentów.'],scope:'stomatologia zachowawcza, endodoncja, protetyka, chirurgia, implantologia'},
  {name:'Izabella Dziubek',role:'lekarz dentysta zajmujący się leczeniem ortodontycznym',image:'/ptak/izabella.jpg',bio:['Absolwentka Uniwersytetu Medycznego w Białymstoku, uczestniczka programu CAD/CAM ZirkonZahn we Włoszech i członkini Polskiego Towarzystwa Periodontologicznego.','Stale rozwija kompetencje na kursach, szczególnie w ortodoncji i periodontologii. Z dużą swobodą przyjmuje również najmłodszych pacjentów.'],scope:'ortodoncja, stomatologia zachowawcza, bonding, stomatologia dziecięca, periodontologia'},
  {name:'Volodymyr Levchuk (Владимир Левчук)',role:'lekarz dentysta, implantolog',image:'/ptak/volodymyr.jpg',bio:['Absolwent Dnipropetrovsk Medical Academy. Od początku pracy rozwija się w stomatologii zachowawczej i implantologii, a szkolenia poszerzyły jego praktykę o protetykę i ortodoncję.','Prowadzi kompleksowe leczenie, wykorzystując nowoczesną diagnostykę i metody terapeutyczne.'],scope:'stomatologia zachowawcza, implantologia, protetyka'},
  {name:'Marcin Kusto',role:'lekarz dentysta',bio:['Absolwent Collegium Medicum Uniwersytetu Jagiellońskiego. Od 2008 roku zajmuje się szerokim zakresem stomatologii zachowawczej, prostej chirurgii oraz protetyki.','Empatyczne podejście i łatwość nawiązywania kontaktu pomagają dorosłym i dzieciom czuć się swobodnie podczas wizyty.'],scope:'stomatologia zachowawcza, pedodoncja, chirurgia, protetyka'},
  {name:'Aleksandra Surmacz',role:'lekarz dentysta',image:'/ptak/aleksandra-surmacz.jpg',bio:['Absolwentka kierunku lekarsko-dentystycznego Collegium Medicum Uniwersytetu Jagiellońskiego i studiów podyplomowych z medycyny estetycznej.','Stawia na nowoczesne, możliwie mało inwazyjne metody oraz spokojną, komfortową atmosferę leczenia.'],scope:'stomatologia zachowawcza, endodoncja, chirurgia'},
  {name:'Bernard Woźniak',role:'lekarz dentysta',bio:['Absolwent Collegium Medicum Uniwersytetu Jagiellońskiego. Doświadczenie zdobywał również przez dziesięć lat w brytyjskiej South Brent Dental Practice.','Specjalizuje się w precyzyjnym leczeniu pod mikroskopem, szczególnie w endodoncji i stomatologii zachowawczej.'],scope:'stomatologia zachowawcza, endodoncja'},
  {name:'Anna Kurek',role:'lekarz dentysta',image:'/ptak/anna.jpg',bio:['Absolwentka Collegium Medicum Uniwersytetu Jagiellońskiego oraz Śląskiej Wyższej Szkoły Medycznej. Rozwija się w stomatologii estetycznej, rekonstrukcyjnej i endodoncji.','Pracuje z użyciem mikroskopu lub lup, stawiając na precyzję, jakość i indywidualne podejście do pacjenta.'],scope:'stomatologia zachowawcza, stomatologia estetyczna, endodoncja'},
  {name:'Aleksandra Kubicka',role:'lekarz dentysta',image:'/ptak/aleksandra-kubicka.jpeg',bio:['Absolwentka kierunku lekarsko-dentystycznego Uniwersytetu Medycznego w Łodzi. Leczy zachowawczo dorosłych i dzieci oraz prowadzi leczenie endodontyczne.','Podczas zabiegów korzysta z lup lub mikroskopu, dbając o dokładność i komfort pacjenta.'],scope:'stomatologia zachowawcza, endodoncja'},
  {name:'Umida Radjapova-Galushka',role:'dyplomowana higienistka stomatologiczna',image:'/ptak/umida.jpg',bio:['Sumienna i dokładna higienistka oraz asystentka. W pracy kieruje się odpowiedzialnością, empatią i szacunkiem do pacjenta.'],group:'Zespół asystujący'},
  {name:'Weronika Warchał',role:'dyplomowana higienistka stomatologiczna',bio:['Dba o komfort pacjentów i sprawny przebieg wizyt. Podczas higienizacji pokazuje, jak niewielkie zmiany codziennych nawyków mogą poprawić zdrowie uśmiechu.'],group:'Zespół asystujący'},
  {name:'Joanna Zając',role:'dyplomowana asystentka stomatologiczna',image:'/ptak/joanna.jpg',bio:['Z zaangażowaniem dba o fizyczny i psychiczny komfort pacjentów, wyjaśnia przebieg zabiegów i pomaga rozwiewać obawy.'],group:'Zespół asystujący'},
  {name:'Martyna Śliwa',role:'dyplomowana asystentka stomatologiczna',bio:['Asystentka z zamiłowaniem do swojej pracy, czerpiąca satysfakcję z pomagania pacjentom i uczestniczenia w procesie leczenia.'],group:'Zespół asystujący'},
  {name:'Ewelina Wiech',role:'dyplomowana asystentka stomatologiczna',bio:['Najważniejsze są dla niej bezpieczeństwo, spokojna atmosfera wizyty i uśmiech pacjenta po zakończonym zabiegu.'],group:'Zespół asystujący'},
  {name:'Klaudia Smajek',role:'rejestratorka medyczna',image:'/ptak/klaudia.jpg',bio:['Otwarta, kreatywna i pełna optymizmu. Zawsze służy pacjentom pomocą i dba o sprawną, życzliwą obsługę rejestracji.'],group:'Rejestracja i zarządzanie'},
  {name:'Małgorzata Ptak',role:'magister zdrowia publicznego, menadżer gabinetu PTAK STOMATOLOGIA',image:'/ptak/malgorzata.jpg',bio:['Absolwentka Collegium Medicum Uniwersytetu Jagiellońskiego na Wydziale Ochrony Zdrowia. Doświadczenie zdobywała m.in. w Agencji Oceny Technologii Medycznych.','W gabinecie odpowiada za profesjonalną obsługę pacjenta i stałe podnoszenie jakości organizacji pracy.'],group:'Rejestracja i zarządzanie'}
];

function Profile({person,index}) { return <article className={`team-profile ${index%2?'reverse':''} ${person.name==='Klaudia Smajek'?'klaudia-profile':''}`}>
  <div className={`team-profile-photo ${!person.image?'empty':''}`}>{person.image?<img src={person.image} alt={person.name} loading="lazy" decoding="async"/>:<span>{person.name.split(' ').slice(0,2).map(x=>x[0]).join('')}</span>}</div>
  <div className="team-profile-copy"><small>{person.group || 'Lekarze'}</small><h2>{person.name}</h2><h3>{person.role}</h3>{person.bio.map((p,i)=><p key={i}>{p}</p>)}{person.scope&&<div className="team-scope"><b>Zakres usług</b><span>{person.scope}</span></div>}</div>
  </article> }

export default function TeamPage(){return <main><SiteHeader/><PageHero title="Zespół" image="/page-heroes/zespol.webp" position="center 42%"/>
  <section className="team-profiles"><div className="shell"><div className="team-profiles-intro"><p className="eyebrow"><span/> NASI SPECJALIŚCI</p><h2>Doświadczenie, precyzja<br/><em>i uważna opieka.</em></h2></div>{team.map((p,i)=><Profile key={p.name} person={p} index={i}/>)}</div></section>
  <section className="cta-band"><div className="shell"><div><p className="eyebrow light"><span/> PIERWSZY KROK</p><h2>Umów konsultację</h2></div><a className="btn primary" href="/kontakt">Przejdź do rejestracji <ArrowRight/></a></div></section><SiteFooter/></main>}
